version: 2

jobs:
  docs-build:
    docker:
      - image: node:9.11.1
    steps:
      - checkout
      - run:
        name: Install yarn
        command: npm install -g --silent yarn
      - run:
        name: Install dependencies
        command: yarn install
      - run:
        name: Build docs
        command: yarn run build
      - persist_to_workspace:
        root: docs
        paths: .
  docs-deploy:
    docker:
      - image: node:9.11.1
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
        name: Configure git
        command: |
          git config user.email "marcel.nakamine@outlook.com"
          git config user.name "Ci-Build"
      - run:
        name: Deploy docs to master branch
        command: |
          git add docs
          git commit -m "Update docs from CircleCI"
          git push -u origin master
workflows:
  version: 2
  deploy_github_pages:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
